// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlrsypxjguorvlgmbfxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscnN5cHhqZ3VvcnZsZ21iZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNTk5OTgsImV4cCI6MjA1MTgzNTk5OH0.85P0g9tJcqEUrWusD4Jl416Pu9wFDk_A4jd0aOZ0h4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);